### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by RJSprod** [papuSpartan/stable-diffusion-webui-auto-tls-https#1]
I've simply run the install for extension from the latest Auto1111 repo and it fails to install.

I am getting this error preventing complete isntallation:

> stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Roots\\SD Auto\\stable-diffusion-webui\\venv\\Lib\\site-packages\\~ryptography\\hazmat\\bindings\\_openssl.pyd'

After restarting webui with the new argument --enable-insecure-extension-access, i see

>   Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
>   handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
>   Traceback (most recent call last):
>     File "C:\Users\USER1\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
>       self._context.run(self._callback, *self._args)
>     File "C:\Users\USER1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
>       self._sock.shutdown(socket.SHUT_RDWR)
>   ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Something is not working correctly. My web browser tells me that HTTPS for this site is not secure.

**Comment by papuSpartan** [comment]
@RashanJS In the SDWUI console, is this happening around the time it says "installing requirements for webui"? If you could post the full log I may be able to better tell what is going on.

**Comment by papuSpartan** [comment]
@RashanJS If you are passing `--self-sign` like with the non-extension version you should remove that unless you are also passing your own cert and key. Not passing any args other than `--enable-insecure-extension-access` and `--server-name`/`--listen` triggers Usecase 1 now because since it is an extension it assumes you want tls enabled by having the extension enabled.

**Comment by RJSprod** [comment]
@papuSpartan I don't have --self-sign included. just the two you mentioned (I don't have server name set)

The error I'm seeing in the console window is happening after I installed the latest and performed gradio restart. I'm not able to get back to the error I first posted about permissions, perhaps there isnt a retry happening for the file that required permission? The log below is after I started webui with the extension disabled. I then updated to the latest extension and relaunched the webui to see errors in the console.

> To create a public link, set `share=True` in `launch()`.
> Closing server running on port: 7860
> Reloading extensions
> Reloading custom scripts
> Default key/cert pair was already generated by webui
> Certificate trust store ready
> Reloading modules: modules.ui
> Refreshing Model List
> Restarting Gradio
> Running on local URL:  https://0.0.0.0:7860
> 
> To create a public link, set `share=True` in `launch()`.

now with latest extension installed i launch webui

> Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
> handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
> Traceback (most recent call last):
>   File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
>     self._sock.shutdown(socket.SHUT_RDWR)
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
>

**Comment by papuSpartan** [comment]
Just to confirm, you have fully uninstalled the non-extension version? Could you try deleting webui.key and webui.cert from the SDWUI folder and then relaunching?

**Comment by papuSpartan** [comment]
If it is the case that it is just a permission error you could try double checking the permissions of `C:\Roots\SD Auto\stable-diffusion-webui\` in case the user that you have running SDWUI does not have the right permissions

**Comment by RJSprod** [comment]
I have full permission for me as user for the directory. I've performed a complete uninstall  reinstall after removing the key and cert. this is the error I see in the console after gradio restart with the latest extension

> Closing server running on port: 7860
> Reloading extensions
> Reloading custom scripts
> Error loading script: auto_tls.py
> Traceback (most recent call last):
>   File "C:\Roots\SD Auto\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
>     module = script_loading.load_module(scriptfile.path)
>   File "C:\Roots\SD Auto\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
>     exec(compiled, module.__dict__)
>   File "C:\Roots\SD Auto\stable-diffusion-webui\extensions\stable-diffusion-webui-auto-tls-https\scripts\auto_tls.py", line 28, in <module>
>     if not cmd_opts.self_sign:
> AttributeError: 'Namespace' object has no attribute 'self_sign'
> 
> Reloading modules: modules.ui
> Refreshing Model List
> Restarting Gradio
> Running on local URL:  http://0.0.0.0:7860
> 
> To create a public link, set `share=True` in `launch()`.
> 

Also BTW thanks for taking a look at this. so close yet so far for me

**Comment by RJSprod** [comment]
okay so I completely uninstalled  and reinstalled, I'm able to get to the https url now. http no longer works (as expected). I think the issue that I was seeing is resolved by removing cert and key, reinstall extension, and restarting sdwebui console. I think I'm good now and the issue can be closed! I'm not seeing any more errors in console.

**Comment by papuSpartan** [comment]
> okay so I completely uninstalled  and reinstalled, I'm able to get to the https url now. http no longer works (as expected). I think the issue that I was seeing is resolved by removing cert and key, reinstall extension, and restarting sdwebui console. I think I'm good now and the issue can be closed! I'm not seeing any more errors in console. 

Great to hear, I think it was probably the PR installation. I do see that error about the --self-sign option though. Its benign but I'll try supressing it to prevent confusion.

**Comment by papuSpartan** [comment]
`--self-sign` error looks to have been caused by being on an old commit. It seems [at least this commit is needed](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/e5690d0bf2da1f0719ca581cd2e797e9b74db67e) for preloading extension arguments.
