### ISSUE TITLE
Causes control-net to produce bar-code like map images when using LibreWolf browser.

### ISSUE THREAD

**Issue by Xmu2** [papuSpartan/stable-diffusion-webui-auto-tls-https#10]
![scribble-0007](https://user-images.githubusercontent.com/37419761/224151832-5958452b-7d3a-439e-86ce-1ff2ba400e51.png)

not sure if this is an issue on your side, but wanted to post here just in case. 

Thanks for your work on auto-tls-https!

**Comment by papuSpartan** [comment]
Could you post how you are using control net while using the extension? I haven't really used controlnet yet at all and it could help to know in what way you are using it. Also, I'm assuming there were no errors thrown in the console window?

**Comment by Xmu2** [comment]
no errors are thrown, but runnig in https causes controlnet to lose its functionality. controlnet produces different types of maps from existing images and uses those maps to control/guide the image generation. the created barcode like maps have no effect on the outcome and defeat the purpose of controlnet. I need to repost on their git.  I'm new to this sort of activity. Thanks

**Comment by papuSpartan** [comment]
> no errors are thrown, but runnig in https causes controlnet to lose its functionality. controlnet produces different types of maps from existing images and uses those maps to control/guide the image generation. the created barcode like maps have no effect on the outcome and defeat the purpose of controlnet. I need to repost on their git.  I'm new to this sort of activity. Thanks

I installed the extension and tested with a segmentation map model and wasn't able to reproduce  the problem. What type of model(s) were you using and for what mode?

**Comment by Xmu2** [comment]
Interesting!  Okay, so it appears that this problem was caused by the particular browser I have been using recently, Librewolf.  Its a branch of firefox. I tried again using the firefox browser itself and there was no longer an issue. To confirm I tried again with the LibreWolf browser and the problem does still occur.  This might be some security layer they added to firefox.

**Comment by papuSpartan** [comment]
@bhappier 
Can you see if this still happens using a couple different chromium based browsers? It might be related to #5. In the case that it is, it might help to see logs from the browser console.

**Comment by Xmu2** [comment]
Brave and Chromium also don't have this problem. Looks like its isolated to LibreWolf.

**Comment by papuSpartan** [comment]
@bhappier Since this is not happening with Chromium and Firefox I'm going to mark this as unplanned. If you open an issue on librewolf though, feel free to mention me or this issue there and I'll take a look if there are logs posted.
