### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Snazzie** [papuSpartan/stable-diffusion-webui-auto-tls-https#11]
Steps:
1. Launch A111
2. do a text2img generate
3. see error

![image](https://user-images.githubusercontent.com/19627023/229871503-c88ff055-a199-4eed-bbbc-51fa1d3a9f22.png)

**Comment by papuSpartan** [comment]
I'm aware of this issue and will be looking at it this afternoon.

**Comment by papuSpartan** [comment]
From what i've been able to tell so far, it's not the certificate itself, but having to do with internal api routes being wholly missing. I'm unsure exactly why but it at least appears that the progress bar route is not added when the api is set up using tls now. I don't know yet if it's because of an update to gradio, or one of the more recent updates to the webui relating to CORS.

**Comment by papuSpartan** [comment]
Looks like this is the issue gradio-app/gradio#563

**Comment by bharadwaj509** [comment]
Yeah I am getting a similar error but @Snazzie were you able to compile your code? I see https in your url. Did you add your certificates in the launch method and run it successfully?

**Comment by Snazzie** [comment]
> Yeah I am getting a similar error but @Snazzie were you able to compile your code? I see https in your url. Did you add your certificates in the launch method and run it successfully? 

Ive done nothing except installing this extension via A1111 gui. And next time it launched, this issue occurred.

**Comment by bharadwaj509** [comment]
Yeah, So I RDP into the machine and worked with the mic. It is working but I dont know what it is reading. It reads "you" for everything I say.

**Comment by papuSpartan** [comment]
If you are both trying to use this extension with the latest version, you need to disable it for now until this issue is resolved. There is no way to get it to function as it was before until there is a fix from gradio upstream. Otherwise, you will need to use an older commit of the webui. 

You can disable the extension without booting the ui by setting the disabled_extensions array to the following in your webui's config.json:
```
"disabled_extensions": [
        "stable-diffusion-webui-auto-tls-https"
    ],
```

**Comment by hkpD** [comment]
Do you happen to know which version is the latest version that will work with your extension?

**Comment by papuSpartan** [comment]
> Do you happen to know which version is the latest version that will work with your extension?

@hkpD It should work with:
- WebUI: [`e33cace2c2074ef342d027c1f31ffc4b3c3e877e`](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/e33cace2c2074ef342d027c1f31ffc4b3c3e877e)

That's from what I last noted in https://github.com/camenduru/sd-webui-extension-records though so it is out of date. It should work with versions a bit newer as well.

**Comment by hkpD** [comment]
It did not work, but I'm using the [DirectML version](https://github.com/lshqqytiger/stable-diffusion-webui-directml/) by [lshqqytiger](https://github.com/lshqqytiger/). I'm not sure if that makes any difference but it most likely does.

**Comment by papuSpartan** [comment]
@hkpD that fork is currently [also using gradio 3.23](https://github.com/lshqqytiger/stable-diffusion-webui-directml/blob/dae3394497ea810a4601422e8c7f3c74debe4c7c/requirements_versions.txt#L6) so it shouldn't work.

**Comment by hkpD** [comment]
Thank you for leading me toward the right answer. I found a version that works with your extension for now.

**Comment by garrettsutula** [comment]
As far as I can tell you can work around this issue by exporting and trusting the TLS cert as a "Trusted Certificate Authority" on the host OS of the computer you're using to browse to Automatic1111. 

Once I do that, I no longer get a warning in the browser and similarly the secure WebSocket connection (wss) can be established:

![image](https://user-images.githubusercontent.com/11978161/232323565-05d14ed6-b9c7-4dc0-85de-c01a6e6f90d3.png)
![image](https://user-images.githubusercontent.com/11978161/232323627-c97bc758-3d3a-46c5-9892-cf51a41c1801.png)

I don't think this is really related to [gradio app/gradio#563](https://github.com/gradio-app/gradio/issues/563), although it's true that [this env var is important for the automatic1111 server calls to its own endpoints](https://github.com/papuSpartan/stable-diffusion-webui-auto-tls-https/blob/905e93a71cc747b0400a8717f14dc840675f6311/scripts/auto_tls.py#L25). So, if that doesn't work there is [another workaround](https://github.com/gradio-app/gradio/blob/f6d8b98eb72bfb466821cb6ec3d86e513a2fbf44/gradio/blocks.py#L1734) where for now you can manually edit `blocks.py` in your venv or whatever.

I have tested this on Windows & MacOS so far.

**Comment by hkpD** [comment]
> 

I was able to do the same thing, but when I went to generate an image, the certificate error came up. 
Are you able to generate an output? 

This is what I received when I tried your second method for editing the blocks.py file. 

```
Running with TLS
Traceback (most recent call last):
  File "H:\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 353, in <module>
    start()
  File "H:\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 348, in start
    webui.webui()
  File "H:\StableDiffusion\stable-diffusion-webui-directml\webui.py", line 257, in webui
    app, local_url, share_url = shared.demo.launch(
  File "H:\StableDiffusion\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1483, in launch
    requests.get(f"{self.local_url}startup-events", verify=ssl_verify)
NameError: name 'ssl_verify' is not defined
Press any key to continue . . .
```

**Comment by garrettsutula** [comment]
> > 
> 
> I was able to do the same thing, but when I went to generate an image, the certificate error came up. Are you able to generate an output?
> 
> This is what I received when I tried your second method for editing the blocks.py file.
> 
> ```
> Running with TLS
> Traceback (most recent call last):
>   File "H:\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 353, in <module>
>     start()
>   File "H:\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 348, in start
>     webui.webui()
>   File "H:\StableDiffusion\stable-diffusion-webui-directml\webui.py", line 257, in webui
>     app, local_url, share_url = shared.demo.launch(
>   File "H:\StableDiffusion\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1483, in launch
>     requests.get(f"{self.local_url}startup-events", verify=ssl_verify)
> NameError: name 'ssl_verify' is not defined
> Press any key to continue . . .
> ```

Ah, my bad - you're right. I must have somehow been running an older version of a dependency or SOMETHING but I started having the same problem.

FORTUNATELY it led to finding another workaround: https://github.com/gradio-app/gradio/commit/417004f9465aa5182b74093d0f245b4f76159864

This disables cert verification for the http client used to make calls back to itself in the queuing module.

edit: originally linked to a change in utils.py but that was extraneous.

**Comment by hkpD** [comment]
YES! Thank you guys so much! It is all working now and I am able to generate output

**Comment by papuSpartan** [comment]
The Web-socket thing was a problem on my machine. The `ssl_verify=False` patch should work while being completely safe because it is only ignoring verification on **circular** requests (made from webui locally back to itself). I'll keep this issue open until the fix is merged into gradio at the least.

**Comment by garrettsutula** [comment]
Idk how fast it'll get merged but I opened a PR to update gradio and add `--disable-tls-verify` arg

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9907

**Comment by papuSpartan** [comment]
@garrettsutula 
I saw that, it may never be though. If vlad merges it into his fork, I'll probably just swap to primarily supporting auto-tls for vlad's.

**Comment by garrettsutula** [comment]
I'll cherry pick the commits over into that fork & submit a PR ¯\_(ツ)_/¯

**Comment by papuSpartan** [comment]
You should be able to fix this issue now by passing `--disable-tls-verify` in your sdwui launch arguments.
