### ISSUE TITLE
Can this work with No-IP ddns?

### ISSUE THREAD

**Issue by kras95** [papuSpartan/stable-diffusion-webui-auto-tls-https#16]
Hello,

I've been banging my head how to get this to work with a ddns service like No-IP.

Installing the certificate when opening it through my No-IP domain does not enable the SSL, because the domain name does not match localhost. It still shows "Connection is not private" after installing the certificate.

**Comment by papuSpartan** [comment]
It can work with No-Ip or any ddns, your cert just needs to be made for that domain. Also, if you're using an external cert then you need to use the arguments mentioned below use-case #2 in the readme.
