### ISSUE TITLE
login with password

### ISSUE THREAD

**Issue by MiTereKun** [papuSpartan/stable-diffusion-webui-auto-tls-https#17]
It would be incredibly cool to log into the webUI interface using a password!! I just found a way to open the program outside the local network and still without Google and the only limitation is the IP whitelist, but 80% of people don’t even know what it is and they have a dynamic IP and every time you start it you need to add your new IP to the terminal so that bots did not find the site and did not use everything for free
I opened webUI from Ubuntu using the Socat utility - [t.me/s/MiTereKun/39](https://t.me/s/MiTereKun/39)

**Comment by papuSpartan** [comment]
@MiTereKun you can use --gradio-auth to have a login page for the UI, is that not what you're wanting?

**Comment by MiTereKun** [comment]
thanks, looks like I just didn't read the [wiki](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings)
--gradio-auth "user1:pas1, user2:pas2"
