### ISSUE TITLE
It cannot be installed on colab.

### ISSUE THREAD

**Issue by ghost** [papuSpartan/stable-diffusion-webui-auto-tls-https#2]
Thanks for making a great extension.

It cannot be installed due to a problem with the Python version.
The certipie package required by this module can only be installed on Python 3.9 or higher.
But python installed in colab is 3.7

I ended up having to upgrade the version.
Changing the Python version is a cumbersome process.
Is there any other way?

**Comment by ghost** [comment]
I was trying to connect to colab without using gradio and ngrok, but I don't think this issue is necessary.
Sorry for creating an issue

**Comment by papuSpartan** [comment]
> I was trying to connect to colab without using gradio and ngrok, but I don't think this issue is necessary. Sorry for creating an issue

It's no problem. I'll put a note to try and prevent confusion for collab users.
