### ISSUE TITLE
README links to generic disabling warning docs with no answer

### ISSUE THREAD

**Issue by dylanh724** [papuSpartan/stable-diffusion-webui-auto-tls-https#21]
> A. You can simply [tell your browser to add an exception](https://support.google.com/chrome/answer/99020?hl=en&co=GENIE.Platform%3DDesktop). (most browsers have similar steps)

This link doesn't actually have any exception steps - perhaps it was updated to exclude it?

EDIT: Similarly, the other link to the IE6 exception steps are also wildly dated.

**Comment by papuSpartan** [comment]
See #22, I updated those two links. If you think those two are fine then I will merge them.

**Comment by papuSpartan** [comment]
closed by #22
