### ISSUE TITLE
Request to use own internal CA and certificates

### ISSUE THREAD

**Issue by scottb901** [papuSpartan/stable-diffusion-webui-auto-tls-https#24]
Any chance you can add something in there where I can use my own Windows CA and certificates generated from it?

Unless its there and im doing something wrong.

thanks!!

**Comment by papuSpartan** [comment]
There are two ways you could do it. The first way would be to use `--autotls-certs`, which will let you pass an arbitrary number of certs to be trusted. The second would be to create your own bundle file from the certs you would like to be trusted via `--autotls-bundle`.

**Comment by scottb901** [comment]
Thank you for the info! How do I use the --autotls-bundle? What do I point it to? I dont believe I see anything about this in documentation. 

EDIT: Cancel that - Figured it out! thank you for all the help!!!
