### ISSUE TITLE
Is it possible to automatically use Let's Encrypt credentials?

### ISSUE THREAD

**Issue by Pixmi** [papuSpartan/stable-diffusion-webui-auto-tls-https#8]
I have a domain registered from google and cannot use self validating credentials, so i want to use Let's Encrypt, any suggestion or help for me?

**Comment by papuSpartan** [comment]
For that, you would need to find your certificate and accompanying key for [usecase 2](https://github.com/papuSpartan/stable-diffusion-webui-auto-tls-https#usecase-2---bring-your-own-certificate). If you don't already have it, you can follow a guide on how to get a certificate from letsencrypt [like this one](https://www.digitalocean.com/community/tutorials/how-to-use-certbot-standalone-mode-to-retrieve-let-s-encrypt-ssl-certificates-on-ubuntu-20-04).

**Comment by Pixmi** [comment]
Thanks for the reply, that article inspired me and the problem has been solved.
